---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  labels:
    app: flagd
data:
  flags.json: |
    {
      "flags": {
        "my-new-feature": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "off"
        },
        "another-feature": {
          "state": "ENABLED",
          "variants": {
            "red": "#FF0000",
            "blue": "#0000FF"
          },
          "defaultVariant": "blue"
        }
      }
    }
