apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flagd-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`resolve.flagd.minikube`)
      kind: Rule
      services:
        - name: flagd-resolve
          port: 8013
    - match: Host(`sync.flagd.minikube`)
      kind: Rule
      services:
        - name: flagd-sync
          port: 8015
          scheme: h2c
