apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flagd-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ofrep.flagd.minikube`)
      kind: Rule
      services:
        - name: flagd
          port: 8013
    - match: Host(`grpc.flagd.minikube`)
      kind: Rule
      services:
        - name: flagd
          port: 8015
          scheme: h2c
