spring:
  application:
    name: flagd-demo-app
gg:
  jte:
    use-precompiled-templates: true
#    development-mode: true

openfeature:
  flagd:
    config-type: IN_PROCESS # IN_PROCESS/RPC
    rpc:
      host: flagd
      port: 8013
    in-process:
      host: flagd
      port: 8015
    deadline: 3000
