spring:
  application:
    name: flagd-demo-app

  jte:
    development-mode: true

openfeature:
  flagd:
    config-type: IN_PROCESS # IN_PROCESS/RPC
    rpc:
      host: localhost
      port: 8013
    in-process:
      host: localhost
      port: 8015
